### PR TITLE
test(chandan)

### PR DESCRIPTION
**Pull request by flychand**
<h1>hello all</h1>
<h2>hello all</h2>

### CODE REVIEW

**Review by johntoppo — COMMENTED** [review]
nice work chandu

**Comment by johntoppo** [comment]
add head and title after html
dude

**Review by flychand — COMMENTED** [review]
i hope you are now satisfied....!!

**Comment by johntoppo** [comment]
<!DOCTYPE>
 <html>
<head>
<title>
 hello 
</title>
</head>
<body>
<h1> hello world</h1>
</body>
</html>

**Comment by spandangithub2016** [comment]
How will i create a pull request tell me the steps

**Comment by johntoppo** [comment]
it is very simple spandan
chandan will tell you the step

**Comment by spandangithub2016** [comment]
okz Thank You

spandy

**Pull request closed without merging**
